/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.RepresentanteDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Representante;

/**
 *
 * @author aleja
 */
public class VentanaModificarRepresentante extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificarRepresentante
     */
    public VentanaModificarRepresentante() {
        initComponents();
    }
    
    private void actualizarTablaRepresentantes() {
    RepresentanteDAO dao = new RepresentanteDAO();
    DefaultTableModel model = (DefaultTableModel) tableRepresentantes.getModel();
    model.setRowCount(0);
    dao.listarRepresentantes().forEach(rep -> {
        model.addRow(new Object[] {
            rep.getNombre(),
            rep.getRut(),
            rep.getNacionalidad()
        });
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRepresentantes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarRut = new javax.swing.JTextField();
        btnModificar1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jLabel1.setText("Rut Empresa a Modificar");

        btnModificar.setText("Modificar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableRepresentantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Rut", "Nacionalidad"
            }
        ));
        jScrollPane1.setViewportView(tableRepresentantes);

        jLabel2.setText("Rut Representante a Modificar");

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar1)
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
    int filaSeleccionada = tableRepresentantes.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un representante de la tabla.");
        return;
    }

    String rut = tableRepresentantes.getValueAt(filaSeleccionada, 1).toString();
    RepresentanteDAO dao = new RepresentanteDAO();
    Representante representante = dao.buscarPorRut(rut); // Método en RepresentanteDAO
    if (representante == null) {
        JOptionPane.showMessageDialog(this, "Representante no encontrado.");
        return;
    }

    String nuevoNombre = JOptionPane.showInputDialog("Ingrese nuevo nombre:", representante.getNombre());
    String nuevaNacionalidad = JOptionPane.showInputDialog("Ingrese nueva nacionalidad (Chilena/Extranjera):", representante.getNacionalidad());

    representante.setNombre(nuevoNombre != null ? nuevoNombre : representante.getNombre());
    representante.setNacionalidad(nuevaNacionalidad != null ? nuevaNacionalidad : representante.getNacionalidad());

    String resultado = dao.modificarRepresentante(representante);
    JOptionPane.showMessageDialog(this, resultado);

    actualizarTablaRepresentantes();
    }//GEN-LAST:event_btnModificar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRepresentantes;
    private javax.swing.JTextField txtBuscarRut;
    // End of variables declaration//GEN-END:variables
}

