/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.EmpresaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author benja
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemRegistrarEmpresa = new javax.swing.JMenuItem();
        menuItemModificarEmpresa = new javax.swing.JMenuItem();
        menuItemMostrarEmpresas = new javax.swing.JMenuItem();
        menuItemEliminarEmpresa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemRegistrarRepresentante = new javax.swing.JMenuItem();
        menuItemModificarRepresentante = new javax.swing.JMenuItem();
        menuItemMostrarRepresentantes = new javax.swing.JMenuItem();
        menuItemEliminarRepresentante = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemEstadisticasEmpresasActivas = new javax.swing.JMenuItem();
        menuItemPromedioInicioActividades = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA CONTABLE");
        jLabel1.setAlignmentY(1.0F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Empresas");

        menuItemRegistrarEmpresa.setText("Registrar");
        menuItemRegistrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRegistrarEmpresa);

        menuItemModificarEmpresa.setText("Modificar");
        menuItemModificarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemModificarEmpresa);

        menuItemMostrarEmpresas.setText("Mostrar");
        menuItemMostrarEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMostrarEmpresasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemMostrarEmpresas);

        menuItemEliminarEmpresa.setText("Eliminar");
        menuItemEliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEliminarEmpresa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Representantes");

        menuItemRegistrarRepresentante.setText("Registrar");
        menuItemRegistrarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarRepresentanteActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemRegistrarRepresentante);

        menuItemModificarRepresentante.setText("Modificar");
        menuItemModificarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarRepresentanteActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemModificarRepresentante);

        menuItemMostrarRepresentantes.setText("Mostrar");
        menuItemMostrarRepresentantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMostrarRepresentantesActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemMostrarRepresentantes);

        menuItemEliminarRepresentante.setText("Eliminar");
        menuItemEliminarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarRepresentanteActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEliminarRepresentante);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estadisticas");

        menuItemEstadisticasEmpresasActivas.setText("Cantidad Empresas Activas");
        menuItemEstadisticasEmpresasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEstadisticasEmpresasActivasActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemEstadisticasEmpresasActivas);

        menuItemPromedioInicioActividades.setText("Promedio Inicio Actividades");
        menuItemPromedioInicioActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPromedioInicioActividadesActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemPromedioInicioActividades);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRegistrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarEmpresaActionPerformed
    VentanaRegistrarEmpresa ventana = new VentanaRegistrarEmpresa();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarEmpresaActionPerformed

    private void menuItemModificarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarEmpresaActionPerformed
    VentanaModificarEmpresa ventana = new VentanaModificarEmpresa();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemModificarEmpresaActionPerformed

    private void menuItemEliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarEmpresaActionPerformed
    VentanaEliminarEmpresa ventana = new VentanaEliminarEmpresa();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarEmpresaActionPerformed

    private void menuItemMostrarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMostrarEmpresasActionPerformed
    VentanaMostrarEmpresa ventana = new VentanaMostrarEmpresa();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemMostrarEmpresasActionPerformed

    private void menuItemRegistrarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarRepresentanteActionPerformed
    VentanaRegistrarRepresentante ventana = new VentanaRegistrarRepresentante();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarRepresentanteActionPerformed

    private void menuItemModificarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarRepresentanteActionPerformed
    VentanaModificarRepresentante ventana = new VentanaModificarRepresentante();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemModificarRepresentanteActionPerformed

    private void menuItemEliminarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarRepresentanteActionPerformed
    VentanaEliminarRepresentante ventana = new VentanaEliminarRepresentante();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarRepresentanteActionPerformed

    private void menuItemMostrarRepresentantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMostrarRepresentantesActionPerformed
    VentanaMostrarRepresentante ventana = new VentanaMostrarRepresentante();
    ventana.setVisible(true);
    }//GEN-LAST:event_menuItemMostrarRepresentantesActionPerformed

    private void menuItemEstadisticasEmpresasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEstadisticasEmpresasActivasActionPerformed
    EmpresaDAO dao = new EmpresaDAO();
    int cantidad = dao.cantidadEmpresasActivas();
    JOptionPane.showMessageDialog(this, "Cantidad de Empresas Activas: " + cantidad, "Estadística", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemEstadisticasEmpresasActivasActionPerformed

    private void menuItemPromedioInicioActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPromedioInicioActividadesActionPerformed
    EmpresaDAO dao = new EmpresaDAO();
    double promedio = dao.promedioInicioActividades();
    JOptionPane.showMessageDialog(this, "Promedio de Inicio de Actividades: " + promedio, "Estadística", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemPromedioInicioActividadesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemEliminarEmpresa;
    private javax.swing.JMenuItem menuItemEliminarRepresentante;
    private javax.swing.JMenuItem menuItemEstadisticasEmpresasActivas;
    private javax.swing.JMenuItem menuItemModificarEmpresa;
    private javax.swing.JMenuItem menuItemModificarRepresentante;
    private javax.swing.JMenuItem menuItemMostrarEmpresas;
    private javax.swing.JMenuItem menuItemMostrarRepresentantes;
    private javax.swing.JMenuItem menuItemPromedioInicioActividades;
    private javax.swing.JMenuItem menuItemRegistrarEmpresa;
    private javax.swing.JMenuItem menuItemRegistrarRepresentante;
    // End of variables declaration//GEN-END:variables
}
