/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.EmpresaDAO;
import controlador.RepresentanteDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empresa;
import modelo.Representante;

/**
 *
 * @author Aleja
 */
public class VentanaModificarEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificarEmpresa
     */
    public VentanaModificarEmpresa() {
        initComponents();
    }
private void actualizarTablaEmpresas() {
    EmpresaDAO dao = new EmpresaDAO();
    DefaultTableModel model = (DefaultTableModel) tableEmpresas.getModel();
    model.setRowCount(0);
    dao.listarEmpresas().forEach(emp -> {
        model.addRow(new Object[] {
            emp.getNombre(),
            emp.getRut(),
            emp.getGiro(),
            emp.getComuna(),
            emp.getRepresentante().getRut()
        });
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmpresas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarRut = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Rut", "Giro", "Comuna", "Representante"
            }
        ));
        jScrollPane1.setViewportView(tableEmpresas);

        jLabel1.setText("Rut Empresa a Modificar");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuscarRut))
                        .addGap(123, 123, 123)
                        .addComponent(btnModificar)
                        .addGap(28, 28, 28)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnModificar)
                                .addComponent(btnVolver)))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    int filaSeleccionada = tableEmpresas.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una empresa de la tabla.");
        return;
    }

    String nombre = tableEmpresas.getValueAt(filaSeleccionada, 0).toString();
    String rut = tableEmpresas.getValueAt(filaSeleccionada, 1).toString();
    String giro = tableEmpresas.getValueAt(filaSeleccionada, 2).toString();
    String comuna = tableEmpresas.getValueAt(filaSeleccionada, 3).toString();
    String representanteRut = tableEmpresas.getValueAt(filaSeleccionada, 4).toString();

    EmpresaDAO dao = new EmpresaDAO();
    RepresentanteDAO representanteDAO = new RepresentanteDAO();

    Representante representante = representanteDAO.buscarPorRut(representanteRut);
    if (representante == null) {
        JOptionPane.showMessageDialog(this, "Representante no encontrado.");
        return;
    }

    Empresa empresa = new Empresa(rut, nombre, giro, comuna, true, 0, 0, representante);
    String nuevoNombre = JOptionPane.showInputDialog("Ingrese nuevo nombre:", nombre);
    String nuevoGiro = JOptionPane.showInputDialog("Ingrese nuevo giro:", giro);
    String nuevaComuna = JOptionPane.showInputDialog("Ingrese nueva comuna:", comuna);

    empresa.setNombre(nuevoNombre != null ? nuevoNombre : nombre);
    empresa.setGiro(nuevoGiro != null ? nuevoGiro : giro);
    empresa.setComuna(nuevaComuna != null ? nuevaComuna : comuna);

    String resultado = dao.modificarEmpresa(empresa);
    JOptionPane.showMessageDialog(this, resultado);

    actualizarTablaEmpresas();
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmpresas;
    private javax.swing.JTextField txtBuscarRut;
    // End of variables declaration//GEN-END:variables
}

