
import java.sql.*;
import javax.swing.JOptionPane;


public class PrincipalRentCar extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalRentCar
     */
    public PrincipalRentCar() {
        initComponents();
        listarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfPatente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jchbNuevo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        JButton.setText("Insertar");
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });
        jPanel1.add(JButton);
        JButton.setBounds(260, 290, 51, 24);

        jLabel1.setText("Patente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 90, 70, 20);
        jPanel1.add(jtfPatente);
        jtfPatente.setBounds(20, 110, 70, 30);

        jLabel2.setText("Marca");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 160, 70, 20);

        jtfMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(jtfMarca);
        jtfMarca.setBounds(20, 180, 140, 24);

        jLabel3.setText("Precio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 230, 70, 20);

        jtfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(jtfPrecio);
        jtfPrecio.setBounds(20, 250, 140, 24);

        jchbNuevo.setText("Nuevo");
        jchbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jchbNuevo);
        jchbNuevo.setBounds(100, 110, 61, 24);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 290, 58, 24);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(410, 290, 54, 24);

        jtaDatos.setColumns(20);
        jtaDatos.setRows(5);
        jScrollPane1.setViewportView(jtaDatos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 100, 300, 180);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentcar", "root", "Duoc.2023")){
            //System.out.println("Conectado!.");
            String sql = "insert into vehiculo values (?, ?, ?, ?)";
            try(PreparedStatement ps = con.prepareStatement(sql)){
                ps.setString(1, jtfPatente.getText());
                ps.setString(2, jtfMarca.getText());
                ps.setString(3, jtfPrecio.getText());
                ps.setBoolean(4, jchbNuevo.isSelected());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Datos Insertados!.");
            }
        }catch(SQLException sqle){
            System.out.println("Error al conectar: " + sqle);
        }
    }//GEN-LAST:event_JButtonActionPerformed

    private void jchbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbNuevoActionPerformed

    private void jtfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentcar", "root", "Duoc.2023")){
            //System.out.println("Conectado!.");
            String sql = "update vehiculo set marca=?, precio=?, nuevo=? where patente=? ";
            try(PreparedStatement ps = con.prepareStatement(sql)){
                ps.setString(4, jtfPatente.getText());
                ps.setString(1, jtfMarca.getText());
                ps.setString(2, jtfPrecio.getText());
                ps.setBoolean(3, jchbNuevo.isSelected());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Datos Actualizados!.");
            }
        }catch(SQLException sqle){
            System.out.println("Error al conectar: " + sqle);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentcar", "root", "Duoc.2023")){
            //System.out.println("Conectado!.");
            String sql = "delete from vehiculo where patente=?";
            try(PreparedStatement ps = con.prepareStatement(sql)){
                ps.setString(1, jtfPatente.getText());
                if(JOptionPane.showConfirmDialog(this, "Seguro de eliminar?") ==0){
                   ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Datos Eliminados!."); 
                }
                
            }
        }catch(SQLException sqle){
            System.out.println("Error al conectar: " + sqle);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMarcaActionPerformed
        public final void listarDatos(){
            jtaDatos.setText("");
             try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentcar", "root", "Duoc.2023")){
            //System.out.println("Conectado!.");
            String sql = "select * from vehiculo";
            try(PreparedStatement ps = con.prepareStatement(sql)){
               try(ResultSet rs = ps.executeQuery()){
                   while(rs.next()){
                       jtaDatos.setText(jtaDatos.getText()
                               +rs.getString("patente")+ " "
                               +rs.getString("marca")+" "
                               +rs.getString("precio")+" " 
                               +rs.getString("nuevo")+"\n "
                       );
                   }
               }
            }
        }catch(SQLException sqle){
            System.out.println("Error al conectar: " + sqle);
        }
        }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalRentCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchbNuevo;
    private javax.swing.JTextArea jtaDatos;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfPatente;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables
}
